[project]
name = "hedonic"
version = "0.0.10"
description = "A Python library for hedonic games"
readme = "README.md"
authors = [
    { name = "Lucas Lopes Felipe" }
]
requires-python = ">=3.12"
dependencies = [
    "lucas-igraph==1.0.0.2",
    "numpy",
]

[project.optional-dependencies]
experiments = [
    "pandas>=2.0.0",
    "scipy>=1.10.0",
    "tqdm>=4.65.0",
    "stopwatch-py>=1.0.0",
    "matplotlib>=3.7",
    "seaborn>=0.13",
    "networkx>=3.2",
    "demon>=2.0.6",
    "cvxpy>=1.7,<2",
]

[project.scripts]
hedonic-exp = "hedonic.experiments.CLI:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
