#!/usr/bin/env python3
"""Generate manuscript TeX tables from a complete GT-robustness ledger.

The detector command owns the condition ledger.  This small report builder is
deliberately detector-free: it verifies the canonical coverage and identity
gates, then creates TeX fragments under ``<output>/paper``. Publication plots
are generated by the experiment runner from the same gated in-memory rows.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
from statistics import mean, stdev
from typing import Any

from hedonic.experiments.overlapping.ground_truth_robustness import (
    _publication_evidence_index,
)


DATASET_ORDER = ["amazon", "dblp", "livejournal", "youtube", "wikipedia"]
DATASET_LABELS = {
    "amazon": "Amazon",
    "dblp": "DBLP",
    "livejournal": "LiveJournal",
    "youtube": "YouTube",
    "wikipedia": "Wikipedia",
}
PHASE_ORDER = ["local", "multiphase"]
POLICY_ORDER = ["fixed_labels", "open_labels"]
COLORS = {"local": "#3366aa", "multiphase": "#d97706"}
MARKERS = {"fixed_labels": "o", "open_labels": "s"}
PROTOCOL = "canonical_unique_cover_v3"


def _json_hash(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _file_hash(path: Path) -> str:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError as exc:
        raise ValueError(f"missing publication artifact: {path}") from exc


def _float(value: Any) -> float | None:
    if value in (None, "", "nan", "NaN"):
        return None
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def _int(value: Any) -> int | None:
    result = _float(value)
    return int(result) if result is not None else None


def _read_coverage(root: Path) -> dict[str, Any]:
    path = root / "coverage_report.json"
    try:
        coverage = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"missing or invalid canonical coverage report: {path}") from exc
    if (
        not isinstance(coverage, dict)
        or coverage.get("protocol") != PROTOCOL
        or coverage.get("canonical_protocol_complete") is not True
        or coverage.get("condition_coverage_complete") is not True
        or coverage.get("all_results_available") is not True
    ):
        raise ValueError(
            "report generation requires a complete canonical v3 detector ledger"
        )
    return coverage


def _read_csv(
    path: Path, coverage: dict[str, Any]
) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    expected_file_hash = (coverage.get("artifact_sha256") or {}).get(
        "results.csv"
    )
    if not isinstance(expected_file_hash, str) or _file_hash(path) != expected_file_hash:
        raise ValueError("results.csv bytes do not match the canonical coverage report")
    with path.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    protocols = {str(row.get("protocol", "")) for row in rows}
    if protocols != {PROTOCOL}:
        raise ValueError(
            f"{path} is not a pure {PROTOCOL} ledger; found protocols {sorted(protocols)}"
        )
    identity = coverage.get("protocol_identity") or {}
    expected_count = int(coverage.get("expected_detector_conditions", -1))
    axis_keys = [str(row.get("condition_axis_key", "")) for row in rows]
    if (
        len(rows) != expected_count
        or len(axis_keys) != len(set(axis_keys))
        or _json_hash(sorted(axis_keys))
        != coverage.get("expected_condition_axis_keys_sha256")
    ):
        raise ValueError("results.csv does not match the exact covered condition grid")
    allowed_statuses = {"completed", "completed_non_equilibrium", "unsupported_cleanup"}
    if any(str(row.get("status", "")) not in allowed_statuses for row in rows):
        raise ValueError("results.csv contains an unregistered terminal status")
    expected_lock = identity.get("protocol_lock_sha256")
    expected_tracked = identity.get("tracked_files_sha256")
    expected_grid = identity.get("effective_grid_sha256")
    if any(
        row.get("protocol_lock_sha256") != expected_lock
        or row.get("tracked_files_sha256") != expected_tracked
        or row.get("effective_grid_sha256") != expected_grid
        or str(row.get("canonical_grid", "")).lower() != "true"
        for row in rows
    ):
        raise ValueError("results.csv mixes foreign or non-canonical identities")
    return rows


def _read_ground_truth(
    root: Path, coverage: dict[str, Any]
) -> list[dict[str, Any]]:
    protocol_identity = coverage.get("protocol_identity") or {}
    expected_hashes = coverage.get("ground_truth_records_sha256") or {}
    if not isinstance(expected_hashes, dict) or not expected_hashes:
        raise ValueError("coverage report does not bind ground-truth record bytes")
    rows: list[dict[str, Any]] = []
    for path in sorted((root / "ground_truth").glob("*.json")):
        relative = path.relative_to(root).as_posix()
        expected_hash = expected_hashes.get(relative)
        if not isinstance(expected_hash, str) or _file_hash(path) != expected_hash:
            raise ValueError(f"ground-truth record bytes are not covered: {path}")
        payload = json.loads(path.read_text())
        if payload.get("status") != "completed":
            continue
        if payload.get("protocol") != PROTOCOL:
            raise ValueError(
                f"{path} belongs to protocol {payload.get('protocol')!r}, not {PROTOCOL}"
            )
        if payload.get("protocol_identity") != protocol_identity:
            raise ValueError(f"{path} has a foreign protocol identity")
        policies = payload.get("policies", {})
        rows.append(
            {
                "dataset": payload.get("dataset"),
                "cover": payload.get("cover"),
                "n_vertices": payload.get("n_vertices"),
                "n_edges": payload.get("n_edges"),
                "n_communities": policies.get("fixed_labels", {}).get("at_density", {}).get("n_communities"),
                "cap": payload.get("effective_max_memberships"),
                "fixed": policies.get("fixed_labels", {}).get("endpoint", {}).get("robust_fraction_gamma_0_1"),
                "open": policies.get("open_labels", {}).get("endpoint", {}).get("robust_fraction_gamma_0_1"),
            }
        )
    if set(expected_hashes) != {
        path.relative_to(root).as_posix()
        for path in (root / "ground_truth").glob("*.json")
    }:
        raise ValueError("ground-truth record set differs from canonical coverage")
    expected_datasets = set(
        (protocol_identity.get("effective_grid") or {}).get("datasets") or []
    )
    expected_cover = str(
        (protocol_identity.get("effective_grid") or {}).get("cover") or ""
    )
    expected_paths = {
        f"ground_truth/{dataset}-{expected_cover}.json"
        for dataset in expected_datasets
    }
    actual_paths = {
        path.relative_to(root).as_posix()
        for path in (root / "ground_truth").glob("*.json")
    }
    if (
        set(expected_hashes) != expected_paths
        or actual_paths != expected_paths
        or len(rows) != int(coverage.get("ground_truth_instances", -1))
        or {str(row.get("dataset")) for row in rows} != expected_datasets
    ):
        raise ValueError("ground-truth rows do not match the canonical dataset grid")
    return rows


def _verify_bound_outputs(root: Path, coverage: dict[str, Any]) -> None:
    expected_artifacts = coverage.get("artifact_sha256") or {}
    required_artifacts = {
        "results.jsonl",
        "results.csv",
        "ground_truth_summary.csv",
    }
    if set(expected_artifacts) != required_artifacts:
        raise ValueError("canonical coverage does not bind the complete flat export set")
    for relative, expected_hash in expected_artifacts.items():
        if not isinstance(expected_hash, str) or _file_hash(root / relative) != expected_hash:
            raise ValueError(f"flat export bytes are not covered: {relative}")
    expected_plots = coverage.get("plot_sha256") or {}
    required = {
        "plots/gt_robustness_overview.png",
        "plots/gt_robustness_overview.pdf",
        "plots/gt_equilibrium_tradeoff.png",
        "plots/gt_equilibrium_tradeoff.pdf",
    }
    if set(expected_plots) != required:
        raise ValueError("canonical coverage does not bind the complete plot set")
    for relative, expected_hash in expected_plots.items():
        if not isinstance(expected_hash, str) or _file_hash(root / relative) != expected_hash:
            raise ValueError(f"publication plot bytes are not covered: {relative}")
    try:
        manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError("missing or invalid canonical manifest") from exc
    if (
        manifest.get("canonical_protocol_complete") is not True
        or manifest.get("protocol_identity") != coverage.get("protocol_identity")
        or manifest.get("artifact_sha256") != coverage.get("artifact_sha256")
        or manifest.get("ground_truth_records_sha256")
        != coverage.get("ground_truth_records_sha256")
        or manifest.get("run_records_sha256")
        != coverage.get("run_records_sha256")
        or manifest.get("referenced_artifacts_sha256")
        != coverage.get("referenced_artifacts_sha256")
        or manifest.get("plot_sha256") != expected_plots
    ):
        raise ValueError("manifest and canonical coverage report disagree")


def _verify_detailed_evidence(
    root: Path, rows: list[dict[str, Any]], coverage: dict[str, Any]
) -> None:
    index = _publication_evidence_index(
        root, rows, coverage.get("protocol_identity") or {}
    )
    if (
        not index.get("valid")
        or coverage.get("detailed_evidence_valid") is not True
        or index.get("run_records_sha256")
        != coverage.get("run_records_sha256")
        or index.get("referenced_artifacts_sha256")
        != coverage.get("referenced_artifacts_sha256")
    ):
        raise ValueError(
            "detailed run records or exact-state artifacts fail publication validation"
        )


def _mean_ci(values: list[float | None]) -> tuple[float | None, float | None]:
    clean = [float(value) for value in values if value is not None]
    if not clean:
        return None, None
    if len(clean) < 2:
        return clean[0], 0.0
    return mean(clean), 1.96 * stdev(clean) / math.sqrt(len(clean))


def _fmt(value: Any, digits: int = 3) -> str:
    number = _float(value)
    if number is None:
        return "--"
    return f"{number:.{digits}f}"


def _tex(value: Any) -> str:
    return str(value).replace("_", r"\_")


def _dataset_label(value: Any) -> str:
    key = str(value)
    return DATASET_LABELS.get(key, key.title())


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def _write_tables(root: Path, paper: Path, gt_rows: list[dict[str, Any]], rows: list[dict[str, Any]]) -> None:
    macros = {
        "GTConditionCount": 0,
        "GTObservedCount": len(rows),
        "GTReturnedCount": sum(row.get("status") in {"completed", "completed_non_equilibrium"} for row in rows),
        "GTCertifiedCount": sum(row.get("status") == "completed" for row in rows),
        "GTNonEquilibriumCount": sum(row.get("status") == "completed_non_equilibrium" for row in rows),
        "GTTerminalCount": sum(row.get("status") == "unsupported_cleanup" for row in rows),
        "GTRawMembershipCount": sum(bool(row.get("raw_membership_hash")) for row in rows),
        "GTNormalizationChangedCount": sum(
            str(row.get("normalization_changed", "")).lower() == "true"
            for row in rows
        ),
        "GTGroundTruthInstances": len(gt_rows),
        "GTDetectorDatasets": len({str(row.get("dataset")) for row in rows}),
        "GTGroundTruthOnlyInstances": max(0, len(gt_rows) - len({str(row.get("dataset")) for row in rows})),
    }
    manifest_path = root / "manifest.json"
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text())
        macros["GTConditionCount"] = int(manifest.get("expected_detector_conditions", len(rows)))
    macro_text = "\n".join(f"\\newcommand{{\\{key}}}{{{value:,}}}" for key, value in macros.items()) + "\n"
    _write_text(paper / "gt_robustness_macros.tex", macro_text)

    gt_lines = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Direct robustness audit of the supplied overlapping covers on the covered-induced analysis graphs.  The cap is the maximum ground-truth membership count (with a minimum of two).  Fixed and open labels are distinct action spaces.}",
        r"\label{tab:gt-robustness}",
        r"\small",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Dataset & Vertices & Edges & Communities & Cap $M$ & Fixed labels & Open labels \\",
        r"\midrule",
    ]
    for row in sorted(gt_rows, key=lambda item: DATASET_ORDER.index(str(item.get("dataset"))) if item.get("dataset") in DATASET_ORDER else 99):
        gt_lines.append(
            f"{_tex(_dataset_label(row.get('dataset', '')))} & {_int(row.get('n_vertices')) or '--'} & "
            f"{_int(row.get('n_edges')) or '--'} & {_int(row.get('n_communities')) or '--'} & "
            f"{_int(row.get('cap')) or '--'} & {_fmt(row.get('fixed'))} & {_fmt(row.get('open'))} \\\\"  # noqa: E501
        )
    gt_lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""])
    _write_text(paper / "gt_ground_truth_table.tex", "\n".join(gt_lines))

    table_lines = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Primary open-label outcomes at $\gamma=$ density. Returns and certificates are raw counts across the four target-distance arms; registered native cleanup-capacity terminal outcomes are not returns and are reported in the coverage manifest. Rates and continuous outcomes first average within target distance and then weight the four distances equally, so the five nonzero perturbation seeds do not dominate the unperturbed arm. Metadata agreement, robustness, and runtime include all native returns; certification is determined by the independent unit-$\ell_2$ regret audit.}",
        r"\label{tab:gt-equilibria}",
        r"\scriptsize",
        r"\begin{tabular}{llrrrrrr}",
        r"\toprule",
        r"Dataset & Phase & Returns & Certified & Balanced cert. & Micro-$F_1$ & Robustness & Runtime (s) \\",
        r"\midrule",
    ]
    for dataset in DATASET_ORDER:
        for phase in PHASE_ORDER:
            for policy in ("open_labels",):
                subset = [
                    row for row in rows
                    if row.get("dataset") == dataset
                    and row.get("phase") == phase
                    and row.get("action_policy") == policy
                    and _float(row.get("resolution_multiplier")) == 1.0
                    and row.get("status") in {"completed", "completed_non_equilibrium"}
                ]
                if not subset:
                    continue
                certified = [row for row in subset if row.get("status") == "completed"]
                distances = sorted(
                    {
                        value
                        for row in subset
                        if (
                            value := _float(
                                row.get("perturbation_target_distance")
                            )
                        )
                        is not None
                    }
                )
                balanced: dict[str, list[float]] = {
                    "certification": [],
                    "f1": [],
                    "robustness": [],
                    "runtime": [],
                }
                for distance in distances:
                    arm = [
                        row
                        for row in subset
                        if _float(row.get("perturbation_target_distance"))
                        == distance
                    ]
                    balanced["certification"].append(
                        sum(row.get("status") == "completed" for row in arm)
                        / len(arm)
                    )
                    for name, key in (
                        ("f1", "accuracy_node_micro_f1"),
                        ("robustness", "robust_fraction_gamma_0_1"),
                        ("runtime", "detector_runtime_seconds"),
                    ):
                        values = [
                            value
                            for row in arm
                            if (value := _float(row.get(key))) is not None
                        ]
                        if values:
                            balanced[name].append(mean(values))
                certification = mean(balanced["certification"])
                f1 = mean(balanced["f1"])
                robust = mean(balanced["robustness"])
                runtime = mean(balanced["runtime"])
                table_lines.append(
                    f"{_tex(_dataset_label(dataset))} & {phase} & {len(subset)} & "
                    f"{len(certified)} & {_fmt(certification, 2)} & {_fmt(f1)} & {_fmt(robust)} & {_fmt(runtime, 2)} \\\\"  # noqa: E501
                )
    table_lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""])
    _write_text(paper / "gt_equilibrium_table.tex", "\n".join(table_lines))


def _save(fig: Any, directory: Path, stem: str) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    fig.savefig(directory / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(directory / f"{stem}.png", dpi=220, bbox_inches="tight")


def _write_figures(root: Path, paper: Path, gt_rows: list[dict[str, Any]], rows: list[dict[str, Any]]) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    plot_dir = paper / "plots"
    valid = [row for row in rows if row.get("status") in {"completed", "completed_non_equilibrium"}]

    # Direct ground-truth robustness.
    fig, axis = plt.subplots(figsize=(7.2, 4.0))
    x = np.arange(len(gt_rows))
    width = 0.36
    fixed = [_float(row.get("fixed")) or 0.0 for row in gt_rows]
    opened = [_float(row.get("open")) or 0.0 for row in gt_rows]
    axis.bar(x - width / 2, fixed, width, label="Fixed labels", color="#3366aa")
    axis.bar(x + width / 2, opened, width, label="Open isolation", color="#d97706")
    axis.set_ylim(0, 1)
    axis.set_ylabel("Full-range robust fraction")
    axis.set_xticks(x, [_dataset_label(row.get("dataset", "")) for row in gt_rows], rotation=25, ha="right")
    axis.grid(axis="y", alpha=0.25)
    axis.legend(frameon=False, ncol=2)
    fig.tight_layout()
    _save(fig, plot_dir, "gt_robustness_profiles")
    plt.close(fig)

    # Perturbation basin: open/fixed panels, phase lines for accuracy and robustness.
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 3.7), sharex=True)
    distances = sorted({
        value
        for row in valid
        if (value := _float(row.get("perturbation_target_distance"))) is not None
    })
    for policy, ax in zip(POLICY_ORDER, axes):
        for phase in PHASE_ORDER:
            means_accuracy: list[float | None] = []
            means_robust: list[float | None] = []
            for distance in distances:
                subset = [row for row in valid if row.get("action_policy") == policy and row.get("phase") == phase and _float(row.get("perturbation_target_distance")) == distance]
                means_accuracy.append(_mean_ci([_float(row.get("accuracy_node_micro_f1")) for row in subset])[0])
                means_robust.append(_mean_ci([_float(row.get("robust_fraction_gamma_0_1")) for row in subset])[0])
            ax.plot(distances, means_accuracy, marker="o", color=COLORS[phase], label=f"{phase} accuracy")
            ax.plot(distances, means_robust, marker="x", linestyle="--", color=COLORS[phase], label=f"{phase} robustness")
        ax.set_title("Fixed labels" if policy == "fixed_labels" else "Open isolation")
        ax.set_xlabel("Target labeled-incidence distance")
        ax.set_ylim(0, 1)
        ax.grid(alpha=0.25)
    axes[0].set_ylabel("Mean fraction / F1")
    axes[1].legend(frameon=False, fontsize="x-small", ncol=2)
    fig.tight_layout()
    _save(fig, plot_dir, "gt_perturbation_profiles")
    plt.close(fig)

    # Accuracy--robustness scatter.
    fig, axis = plt.subplots(figsize=(5.4, 4.4))
    for phase in PHASE_ORDER:
        for policy in POLICY_ORDER:
            subset = [row for row in valid if row.get("phase") == phase and row.get("action_policy") == policy]
            xs = [_float(row.get("robust_fraction_gamma_0_1")) for row in subset]
            ys = [_float(row.get("accuracy_node_micro_f1")) for row in subset]
            pairs = [(xv, yv) for xv, yv in zip(xs, ys) if xv is not None and yv is not None]
            if pairs:
                axis.scatter([pair[0] for pair in pairs], [pair[1] for pair in pairs], s=13, alpha=0.36, color=COLORS[phase], marker=MARKERS[policy], label=f"{phase} / {policy.replace('_', ' ')}")
    axis.set_xlim(0, 1)
    axis.set_ylim(0, 1)
    axis.set_xlabel("Final full-range robust fraction")
    axis.set_ylabel("Node micro-$F_1$ vs supplied cover")
    axis.grid(alpha=0.25)
    axis.legend(frameon=False, fontsize="x-small")
    fig.tight_layout()
    _save(fig, plot_dir, "gt_accuracy_robustness")
    plt.close(fig)

    # Runtime and certified-equilibrium rate.
    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.8))
    labels = [_dataset_label(dataset) for dataset in DATASET_ORDER]
    x = np.arange(len(DATASET_ORDER))
    combinations = [(phase, policy) for phase in PHASE_ORDER for policy in POLICY_ORDER]
    width = 0.18
    for index, (phase, policy) in enumerate(combinations):
        rates: list[float] = []
        runtimes: list[float] = []
        for dataset in DATASET_ORDER:
            subset = [row for row in valid if row.get("dataset") == dataset and row.get("phase") == phase and row.get("action_policy") == policy]
            certified = sum(row.get("status") == "completed" for row in subset)
            rates.append(certified / len(subset) if subset else 0.0)
            values = [_float(row.get("detector_runtime_seconds")) for row in subset]
            runtimes.append(mean([value for value in values if value is not None]) if values else 0.0)
        offset = (index - (len(combinations) - 1) / 2) * width
        label = f"{phase} / {policy.replace('_', ' ')}"
        axes[0].bar(x + offset, rates, width, label=label, color=COLORS[phase], alpha=0.65 if policy == "fixed_labels" else 0.95, hatch="" if policy == "fixed_labels" else "//")
        axes[1].bar(x + offset, runtimes, width, label=label, color=COLORS[phase], alpha=0.65 if policy == "fixed_labels" else 0.95, hatch="" if policy == "fixed_labels" else "//")
    axes[0].set_ylabel("Certified fraction")
    axes[0].set_ylim(0, 1)
    axes[1].set_ylabel("Mean detector runtime (s)")
    axes[1].set_yscale("log")
    for axis in axes:
        axis.set_xticks(x, labels, rotation=25, ha="right")
        axis.grid(axis="y", alpha=0.25)
    axes[1].legend(frameon=False, fontsize="xx-small", ncol=2)
    fig.tight_layout()
    _save(fig, plot_dir, "gt_efficiency")
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="GT robustness artifact directory")
    parser.add_argument("--output", type=Path, default=None, help="Output directory (defaults to input)")
    args = parser.parse_args()
    root = args.input.expanduser().resolve()
    output = (args.output or root).expanduser().resolve()
    paper = output / "paper"
    _write_text(paper / "gt_publication_ready.tex", "\\GTResultsReadyfalse\n")
    coverage = _read_coverage(root)
    _verify_bound_outputs(root, coverage)
    protocol_identity = coverage["protocol_identity"]
    gt_rows = _read_ground_truth(root, coverage)
    rows = _read_csv(root / "results.csv", coverage)
    if not rows:
        raise SystemExit(f"no results.csv rows found under {root}")
    _verify_detailed_evidence(root, rows, coverage)
    _write_tables(root, paper, gt_rows, rows)
    _write_text(
        paper / "combined_coverage_report.json",
        json.dumps(
            {
                "detector": coverage,
                "interpretation": (
                    "The canonical v3 ledger contains the four SNAP collections "
                    "with a top5000 metadata cover. Wikipedia exposes only the "
                    "distinct all-category cover and is outside this factorial. "
                    "Zero-swap cells use one perturbation seed because the other "
                    "seeds would reproduce the identical initial cover."
                ),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )
    manifest = {
        "protocol": PROTOCOL,
        "protocol_identity": protocol_identity,
        "source": str(root),
        "rows": len(rows),
        "ground_truth_instances": len(gt_rows),
        "outputs": [str(path.relative_to(output)) for path in sorted(paper.rglob("*")) if path.is_file()],
    }
    _write_text(paper / "report_manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    _write_text(
        paper / "gt_publication_ready.tex",
        "\\GTResultsReadytrue\n",
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
