name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on standard version tags like v0.0.1, v1.0.0, etc.
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read    # Required to read repository contents

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only run when explicitly triggered or when we want TestPyPI publishing
    if: github.event_name == 'workflow_dispatch' || contains(github.ref, 'test')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: 'latest'

      - name: Build package
        run: uv build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # Uses OIDC via the id-token permission; no password/secret needed.
